import{useEffect,useState}from'react'
import{PageHeader,EmptyState}from'../components'
import{api}from'../lib/api'
import{dateTime,roleLabels}from'../lib/labels'
import type{Category,Department,User}from'../types'

const emptyUserForm={name:'',email:'',password:'',role:'EMPLOYEE',departmentId:'',active:true}
export function UsersPage(){
  const[items,setItems]=useState<User[]>([]);const[departments,setDepartments]=useState<Department[]>([]);const[editing,setEditing]=useState<User|null>(null);const[show,setShow]=useState(false);const[error,setError]=useState('');const[form,setForm]=useState(emptyUserForm)
  const load=()=>api.get('/users').then(r=>setItems(r.data));useEffect(()=>{load();api.get('/departments').then(r=>setDepartments(r.data))},[])
  function close(){setShow(false);setEditing(null);setError('');setForm(emptyUserForm)}
  function edit(user:User){setEditing(user);setShow(true);setError('');setForm({name:user.name,email:user.email,password:'',role:user.role,departmentId:user.departmentId??'',active:user.active})}
  async function save(e:React.FormEvent){e.preventDefault();setError('');try{const data={name:form.name,email:form.email,role:form.role,departmentId:form.departmentId||null,active:form.active};if(editing)await api.patch(`/users/${editing.id}`,data);else await api.post('/users',{...data,password:form.password});close();load()}catch(err:any){setError(err.response?.data?.message??'Não foi possível salvar o usuário.')}}
  async function remove(user:User){if(!window.confirm(`Excluir o usuário ${user.name}?`))return;setError('');try{await api.delete(`/users/${user.id}`);load()}catch(err:any){setError(err.response?.data?.message??'Não foi possível excluir o usuário.')}}
  return <div className="page"><PageHeader title="Usuários" action={<button className="button primary" onClick={()=>{close();setShow(true)}}>Novo usuário</button>}/>{error&&<div className="alert error user-alert">{error}</div>}{show&&<form className="inline-form" onSubmit={save}><input required placeholder="Nome" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required type="email" placeholder="E-mail" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/>{!editing&&<input required minLength={8} type="password" placeholder="Senha inicial" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>}<select value={form.role} disabled={editing?.role==='ADMIN'} onChange={e=>setForm({...form,role:e.target.value})}>{Object.entries(roleLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><select value={form.departmentId} onChange={e=>setForm({...form,departmentId:e.target.value})}><option value="">Sem setor</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><button className="button primary">{editing?'Salvar alterações':'Salvar'}</button><button type="button" className="button secondary" onClick={close}>Cancelar</button></form>}<div className="table-wrap"><table><thead><tr><th>Nome</th><th>E-mail</th><th>Perfil</th><th>Setor</th><th>Status</th><th>Criado em</th><th>Ações</th></tr></thead><tbody>{items.map(u=><tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td>{roleLabels[u.role]}</td><td>{u.department?.name??'Sem setor'}</td><td>{u.role==='ADMIN'?<span className="status-toggle active">Ativo</span>:<button className={`status-toggle ${u.active?'active':''}`} onClick={()=>api.patch(`/users/${u.id}`,{active:!u.active}).then(load)}>{u.active?'Ativo':'Inativo'}</button>}</td><td>{dateTime(u.createdAt)}</td><td><div className="table-actions"><button className="link-button" onClick={()=>edit(u)}>Editar</button>{u.role!=='ADMIN'&&<button className="link-button danger" onClick={()=>remove(u)}>Excluir</button>}</div></td></tr>)}</tbody></table></div></div>
}

export function DepartmentsPage(){const[items,setItems]=useState<Department[]>([]);const[name,setName]=useState('');const load=()=>api.get('/departments').then(r=>setItems(r.data));useEffect(()=>{load()},[]);async function add(e:React.FormEvent){e.preventDefault();await api.post('/departments',{name,active:true});setName('');load()}return <div className="page"><PageHeader title="Setores"/><form className="compact-add" onSubmit={add}><label>Nome do setor<input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome"/></label><button className="button primary">Adicionar setor</button></form><div className="table-wrap"><table><thead><tr><th>Nome</th><th>Usuários</th><th>Categorias</th><th>Status</th></tr></thead><tbody>{items.map(d=><tr key={d.id}><td>{d.name}</td><td>{d._count?.users??0}</td><td>{d._count?.categories??0}</td><td><button className={`status-toggle ${d.active?'active':''}`} onClick={()=>api.patch(`/departments/${d.id}`,{active:!d.active}).then(load)}>{d.active?'Ativo':'Inativo'}</button></td></tr>)}</tbody></table></div></div>}

export function CategoriesPage(){const[items,setItems]=useState<Category[]>([]);const[departments,setDepartments]=useState<Department[]>([]);const[form,setForm]=useState({name:'',departmentId:''});const load=()=>api.get('/categories').then(r=>setItems(r.data));useEffect(()=>{load();api.get('/departments').then(r=>setDepartments(r.data))},[]);async function add(e:React.FormEvent){e.preventDefault();await api.post('/categories',{...form,active:true});setForm({name:'',departmentId:''});load()}return <div className="page"><PageHeader title="Categorias"/><form className="compact-add" onSubmit={add}><label>Nome<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Setor<select value={form.departmentId} onChange={e=>setForm({...form,departmentId:e.target.value})}><option value="">Selecione</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><button className="button primary">Adicionar categoria</button></form>{items.length?<div className="table-wrap"><table><thead><tr><th>Nome</th><th>Setor</th><th>Status</th></tr></thead><tbody>{items.map(c=><tr key={c.id}><td>{c.name}</td><td>{c.department?.name}</td><td><button className={`status-toggle ${c.active?'active':''}`} onClick={()=>api.patch(`/categories/${c.id}`,{active:!c.active}).then(load)}>{c.active?'Ativa':'Inativa'}</button></td></tr>)}</tbody></table></div>:<EmptyState>Nenhuma categoria encontrada.</EmptyState>}</div>}

export function ReportsPage(){const[data,setData]=useState<any>(null);useEffect(()=>{api.get('/reports/overview').then(r=>setData(r.data))},[]);if(!data)return null;return <div className="page"><PageHeader title="Relatórios" action={<select><option>Últimos 30 dias</option><option>Hoje</option><option>Últimos 7 dias</option><option>Este mês</option></select>}/><section className="metrics"><div className="metric"><span>Total de chamados</span><strong>{data.total}</strong></div><div className="metric"><span>Em aberto</span><strong>{data.open}</strong></div><div className="metric"><span>Resolvidos</span><strong>{data.resolved}</strong></div><div className="metric"><span>Tempo médio de resolução</span><strong>{data.avgHours.toFixed(1)} h</strong></div><div className="metric"><span>Dentro do SLA</span><strong>{data.withinSla.toFixed(0)}%</strong></div></section><section className="report-grid"><div className="section"><h2>Chamados por prioridade</h2>{data.byPriority.map((i:any)=><div className="bar-row" key={i.priority}><span>{i.priority}</span><div><i style={{width:`${i._count/Math.max(data.total,1)*100}%`}}/></div><strong>{i._count}</strong></div>)}</div><div className="section"><h2>Indicadores de atendimento</h2><dl className="report-list"><div><dt>Chamados pendentes</dt><dd>{data.open}</dd></div><div><dt>Chamados concluídos</dt><dd>{data.resolved}</dd></div><div><dt>Percentual dentro do SLA</dt><dd>{data.withinSla.toFixed(1)}%</dd></div></dl></div></section></div>}

export function ProfilePage(){return <div className="page narrow"><PageHeader title="Minha conta"/><div className="form-card"><p>Os dados de acesso são administrados pelo responsável do sistema.</p></div></div>}
export function SettingsPage(){return <div className="page narrow"><PageHeader title="Configurações"/><div className="form-card"><label>Prazo para reabertura<select defaultValue="7"><option value="7">7 dias</option></select></label><button className="button primary">Salvar alterações</button></div></div>}
