import{zodResolver}from'@hookform/resolvers/zod'
import{useEffect,useState}from'react'
import{useForm}from'react-hook-form'
import{useNavigate}from'react-router-dom'
import{z}from'zod'
import{Breadcrumb,FieldError,PageHeader}from'../components'
import{api}from'../lib/api'
import type{Category,Department,Priority}from'../types'
const schema=z.object({title:z.string().min(3,'Informe o assunto.').max(150),departmentId:z.string().min(1,'Selecione o setor.'),categoryId:z.string().min(1,'Selecione a categoria.'),priority:z.enum(['LOW','MEDIUM','HIGH','URGENT']),description:z.string().min(10,'Descreva a solicitação.').max(5000)})
type Form=z.infer<typeof schema>
export function NewTicketPage(){const navigate=useNavigate();const[departments,setDepartments]=useState<Department[]>([]);const[categories,setCategories]=useState<Category[]>([]);const[apiError,setApiError]=useState('');const{register,watch,handleSubmit,formState:{errors,isSubmitting}}=useForm<Form>({resolver:zodResolver(schema),defaultValues:{priority:'MEDIUM'}});const departmentId=watch('departmentId');useEffect(()=>{api.get('/departments').then(r=>setDepartments(r.data.filter((d:Department)=>d.active)))},[]);useEffect(()=>{if(departmentId)api.get('/categories',{params:{departmentId}}).then(r=>setCategories(r.data.filter((c:Category)=>c.active)));else setCategories([])},[departmentId]);async function submit(data:Form){try{const response=await api.post('/tickets',data);navigate(`/chamados/${response.data.id}`,{state:{message:'Chamado criado com sucesso.'}})}catch{setApiError('Não foi possível criar o chamado.')}}return <div className="page narrow"><Breadcrumb items={[{label:'Chamados',to:'/chamados'},{label:'Abrir chamado'}]}/><PageHeader title="Abrir chamado"/><form className="form-card" onSubmit={handleSubmit(submit)}>{apiError&&<div className="alert error">{apiError}</div>}<label className="full">Assunto<input maxLength={150} {...register('title')}/><FieldError message={errors.title?.message}/></label><label>Setor<select {...register('departmentId')}><option value="">Selecione</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><FieldError message={errors.departmentId?.message}/></label><label>Categoria<select {...register('categoryId')} disabled={!departmentId}><option value="">Selecione</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><FieldError message={errors.categoryId?.message}/></label><label>Prioridade<select {...register('priority')}><option value="LOW">Baixa</option><option value="MEDIUM">Média</option><option value="HIGH">Alta</option><option value="URGENT">Urgente</option></select></label><label className="full">Descrição<textarea rows={8} maxLength={5000} {...register('description')}/><FieldError message={errors.description?.message}/><small className="hint">Até 5.000 caracteres.</small></label><label className="full">Anexos<input type="file" multiple accept=".pdf,.png,.jpg,.jpeg,.doc,.docx,.xls,.xlsx"/><small className="hint">PDF, imagens e documentos de até 10 MB.</small></label><div className="form-actions"><button type="button" className="button secondary" onClick={()=>navigate(-1)}>Cancelar</button><button className="button primary" disabled={isSubmitting}>{isSubmitting?'Abrindo...':'Abrir chamado'}</button></div></form></div>}
