import{useEffect,useState}from'react'
import{Link,useSearchParams}from'react-router-dom'
import{Search}from'lucide-react'
import{useAuth}from'../auth'
import{Loading,PageHeader,TicketTable}from'../components'
import{api}from'../lib/api'
import{priorityLabels,statusLabels}from'../lib/labels'
import type{Priority,Status,Ticket}from'../types'
export function TicketsPage(){const{user}=useAuth();const[params]=useSearchParams();const[tickets,setTickets]=useState<Ticket[]|null>(null);const[filters,setFilters]=useState({search:'',status:'',priority:'',sort:'updated'});useEffect(()=>{api.get('/tickets').then(r=>setTickets(r.data))},[]);if(!tickets)return <Loading/>;let shown=tickets.filter(t=>(!filters.search||`${t.code} ${t.title} ${t.requester.name}`.toLowerCase().includes(filters.search.toLowerCase()))&&(!filters.status||t.status===filters.status)&&(!filters.priority||t.priority===filters.priority));if(params.get('mine'))shown=shown.filter(t=>t.assignedToId===user?.id);if(params.get('unassigned'))shown=shown.filter(t=>!t.assignedToId);shown=[...shown].sort((a,b)=>filters.sort==='oldest'?+new Date(a.createdAt)-+new Date(b.createdAt):filters.sort==='priority'?['LOW','MEDIUM','HIGH','URGENT'].indexOf(b.priority)-['LOW','MEDIUM','HIGH','URGENT'].indexOf(a.priority):+new Date(b.updatedAt)-+new Date(a.updatedAt));return <div className="page"><PageHeader title={user?.role==='EMPLOYEE'?'Meus chamados':'Chamados'} action={<Link className="button primary" to="/chamados/novo">Abrir chamado</Link>}/><div className="filters"><label className="search"><Search/><input placeholder="Buscar por código, assunto ou solicitante" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/></label><select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">Todos os status</option>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select value={filters.priority} onChange={e=>setFilters({...filters,priority:e.target.value})}><option value="">Todas as prioridades</option>{Object.entries(priorityLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select value={filters.sort} onChange={e=>setFilters({...filters,sort:e.target.value})}><option value="updated">Última atualização</option><option value="oldest">Mais antigos</option><option value="priority">Prioridade</option></select></div><section className="section"><div className="result-count">{shown.length} {shown.length===1?'chamado':'chamados'}</div><TicketTable tickets={shown}/></section></div>}
